Worms: Worm Class Reference
Worm Class Reference
This class encapsulates a "worm" which lives, eats, moves, and eventually dies.
#include <Worm.h>
Classes
class Info
Instances of this class encapsulate everything that is different form one kind of Worm to another.
class segment
Instances of this structure encapsulate information about each segment in a worm.
Public Types
typedef Info * UniqueWormType
Type used to uniquely identify each type of worm The fact that this type is a pointer cannot be exploited because the Info type is private to this class.
Public Member Functions
Worm (UniqueWormType typeInfo, std::string saying, int posX, int posY, WormsSim &sim)
Constructs a worm instance with enough segments to store one each character in saying in a different worm segment.
Worm (const Worm &original, int truncationIndex)
Constructs a worm instance that contains copies of the range of segments from the tail up to but not including the segment at truncation index in original.
Non-mutating Accessors
int getFoodValue () const
Returns the neutritional food value of the worm.
int getAttr () const
const segment & getHead () const
const std::vector< segment > & getBody () const
int segmentIndexAt (int x, int y) const
Returns the index of one the worm's segments of one or more of the worm's segments other than segment index 0 occupies the board position, {x, y}.
bool isAlive () const
Functions That Mutate a Worm Instance
void live (WormsSim &sim)
Call to execute one simulation step of the worm's life.
void onWasSlicedAtSegmentIndex (int victimSegmentNumber)
Template Method: called when a worm has been sliced.
void onWasEaten ()
Template Method: called when worm has been eaten As a side effect, this function decrements the count of the number of living instances that have newly eaten worm's type.
Static Public Member Functions
Access Simulation Wide Worm Statistics of Worm Types
static int getNumVegetarians ()
static int getNumCanibals ()
static int getNumScissorheads ()
static void resetWormCounters ()
Static Public Attributes
static const std::vector< UniqueWormType > UniqueWormTypes
This vector contains all possible unique worm types.
Private Types
enum direction {
NORTH =0, NORTHEAST, EAST, SE,
S, SW, W, NW
}
The allowed directions of travel from any board position to an adjacent board positions.
enum status { EATEN, DEAD, ALIVE }
These are the possible statuses for a Worm instance.
Private Member Functions
segment & getHead ()
bool isHungry () const
A Worm is hungry if its stomach foof content value at least 25% less that the worm's stomach capacity.
status getStatus () const
void updateStatusBasedOnStomach ()
Changes the worm's status based on the size of the worm and the amount of food in the worm's stomach.
bool areAllSegmentsContiguous (const WormsSim &sim) const
This function should only be used for pre and post condition assertion checking.
Private Attributes
UniqueWormType m_typeInfo
direction m_direction
int m_stomach
status m_status
std::vector< segment > m_body
Static Private Attributes
static const int foodValueOfCarrot = 2
Nutritional value of each carrot eaten by a worm.
static Info vegetarianInfo
Defines the information that distinguishes Vegetarian worms from other types of worms.
static Info scissorInfo
Defines the information that distinguishes ScissorHead worms from other types of worms.
static Info cannibalInfo
Defines the information that distinguishes Cannibal worms from other types of worms.
Detailed Description
This class encapsulates a "worm" which lives, eats, moves, and eventually dies.
This class collaborates with the WormsSim class to interact with a simulated area called a "board" that potentially contains other worms and "carrots" that worms may eat. Worm instances may interact with each other in several ways, but in every case, the interaction is mediated by an instance of WormsSim i.e. The only way a Worm instance can influence another worm instance or the board is via the functions of WormsSim.
Design Notes:
Following the principle of separation of concerns, this class intentionally does not have any "drawing" dependencies. It is anticipated that many different strategies for "drawing" a sim worm may eventually be implemented. This class is responsible for encapsulating worm state irrespective of drawing implemented elsewhere.
Composition ("has-a") relationships are preferred over inheritance ("is-a") relationships between classes. For example, each Worm has a reference to a UniqueWormType and an arbitrary number of segments. An alternative design might provide an abstract "Worm" class and several distinct subclasses to encapsulate each different “kinds" of worm. However, when replicating the functionality of pmate.nosp@m.ti@w.nosp@m.right.nosp@m..edu's 2013 worms.cpp, the only aspects of a Worm that vary by “kind” may be represented using composition (has-a relationships). Note: A private “inner” class accessible only within the Worm class encapsulates all differences between worm types. The kind of a worm is hidden from and irrelevant to code outside the implementation of the Worm class. It could be argued that if inheritance based polymorphism was used to enable worm kind specialization, hypothetical future Worm subclasses might be implemented as subclasses of Worm, but that is hardly the only or best approach: Future "kinds" could be accommodated through template specialization, the Visitor design pattern, the Command design pattern, or the Adaptor design pattern all of which exist to minimize coupling between code specifically by avoiding unnecessary inheritance.
Definition at line 55 of file Worm.h.
Member Typedef Documentation
typedef Info* Worm::UniqueWormType
Type used to uniquely identify each type of worm The fact that this type is a pointer cannot be exploited because the Info type is private to this class.
This C++ idiom is sometimes called a "handle" i.e. an opaque pointer.
Definition at line 109 of file Worm.h.
Constructor & Destructor Documentation
Worm::Worm (UniqueWormType typeInfo, std::string saying, int posX, int posY, WormsSim & sim)
Constructs a worm instance with enough segments to store one each character in saying in a different worm segment.
This function stores the saying character starting at the worm's head (the first character in saying is stored by the head). As a side effect, this function increases the count of the number of worms with the specified type.
Definition at line 11 of file Worm.cpp.
References areAllSegmentsContiguous(), Worm::Info::count, and WormsSim::getSingletonSim().
Worm::Worm (const Worm & original, int truncationIndex)
Constructs a worm instance that contains copies of the range of segments from the tail up to but not including the segment at truncation index in original.
As a side effect, this function increases the count of the number of worms with the specified type.
Definition at line 52 of file Worm.cpp.
References areAllSegmentsContiguous(), Worm::Info::count, and WormsSim::getSingletonSim().
Member Function Documentation
bool Worm::areAllSegmentsContiguous (const WormsSim & sim) const private
This function should only be used for pre and post condition assertion checking.
This function should only be used to test pre and post conditions of other functions.
Definition at line 372 of file Worm.cpp.
int Worm::getFoodValue () const
Returns the neutritional food value of the worm.
This is the amount of food another worm may obtain by eating this worm. Returns a value proportional to the body size of the worm.
Definition at line 258 of file Worm.cpp.
bool Worm::isHungry () const private
A Worm is hungry if its stomach foof content value at least 25% less that the worm's stomach capacity.
Returns true if the worm is alive and hungry and false otherwise
Definition at line 236 of file Worm.cpp.
void Worm::live (WormsSim & sim)
Call to execute one simulation step of the worm's life.
The number of directions from one board position to any adjacent board position
dx changes, indexed by DIRECTION; (+0 just to line up)
dy changes, indexed by DIRECTION; (+0 just to line up)
Stores DIRECTIONs, a.k.a. indexes into dxa and dya and indirectly controls frequency and direction of turns made by the head because because head movement directions are selected pseudo randomly from this array.
Definition at line 79 of file Worm.cpp.
References areAllSegmentsContiguous(), WormsSim::getRandomModX(), WormsSim::getSingletonSim(), isHungry(), and updateStatusBasedOnStomach().
void Worm::onWasEaten ()
Template Method: called when worm has been eaten As a side effect, this function decrements the count of the number of living instances that have newly eaten worm's type.
Definition at line 183 of file Worm.cpp.
References areAllSegmentsContiguous(), cannibalInfo, Worm::Info::count, WormsSim::getSingletonSim(), scissorInfo, and vegetarianInfo.
int Worm::segmentIndexAt (int x, int y) const
Returns the index of one the worm's segments of one or more of the worm's segments other than segment index 0 occupies the board position, {x, y}.
Returns 0 otherwise.
Definition at line 293 of file Worm.cpp.
void Worm::updateStatusBasedOnStomach () private
Changes the worm's status based on the size of the worm and the amount of food in the worm's stomach.
As a side effect, if the function changes the worm status to DEAD, the function also decrements the count of the number of living instances that have newly deceased worm's type.
Definition at line 271 of file Worm.cpp.
References areAllSegmentsContiguous(), Worm::Info::count, and WormsSim::getSingletonSim().
Member Data Documentation
Worm::Info Worm::cannibalInfo static private
Initial value:
= {
    Worm::Info::CannibalEat,
    3, 5, 4
}
Defines the information that distinguishes Cannibal worms from other types of worms.
Definition at line 102 of file Worm.h.
Worm::Info Worm::scissorInfo static private
Initial value:
= {
    Worm::Info::ScissorEat,
    2, 4, 5
}
Defines the information that distinguishes ScissorHead worms from other types of worms.
Definition at line 101 of file Worm.h.
const std::vector< Worm::UniqueWormType > Worm::UniqueWormTypes static
Initial value:
= {
    &Worm::vegetarianInfo,
    &Worm::scissorInfo,
    &Worm::cannibalInfo,
}
This vector contains all possible unique worm types.
An immutable collection of all available worm types.
Definition at line 112 of file Worm.h.
Worm::Info Worm::vegetarianInfo static private
Initial value:
= {
    Worm::Info::VegetarianEat,
    1, 3, 3
}
Defines the information that distinguishes Vegetarian worms from other types of worms.
Definition at line 100 of file Worm.h.
The documentation for this class was generated from the following files:
Worm.h
Worm.cpp