Worms: WormsSim Class Reference
WormsSim Class Reference
WormSim encapsulates the board and zero or more Worm instances.
#include <WormsSim.h>
Classes
struct square
A "board" is a 2D array of square instances.
Public Member Functions
Non-mutating Accessors
const std::vector< Worm > & getWorms () const
int getWidth () const
int getHeight () const
int getHighWaterMark () const
const char getOnecAt (int x, int y) const
const char getAttrAt (int x, int y) const
Functions that mutate the simulation
void runSimulation (AbstractWormsSimUIStrategy &uiStrategy)
Each time this function is called, the simulation restarts from initial conditions with a pseudo random number of generated worms and a board containing a carrot at every position.
void createWorm ()
bool tryToEatCarrotAt (int x, int y)
void sliceVictimForWorm (Worm &worm)
int eatVictimForWorm (Worm &worm)
Static Public Member Functions
static WormsSim & initSingletonSim (int width, int height)
This function creates an instance of WormsSim with the specified board width and height.
static WormsSim & getSingletonSim ()
This function should only be used for pre and post condition assertion checking.
static unsigned int getRandomModX (unsigned int x)
Utility function to return a pseudo random natural number in the range 0..(x-1).
static int getMaxBoardHeight ()
Returns the maximum number of rows of squares in a "board".
static int getMaxBoardWidth ()
Returns the maximum number of columns of squares in a "board".
Private Types
typedef std::array< square, max_board_height > board_column
The type of a single column in the simulation's board.
typedef std::array< board_column, max_board_width > board
The type of the simulation's board.
Private Member Functions
std::vector< Worm >::size_type findSlot () const
Use this function to find an index where a non-living Worm can be replaced by a new living worm.
void updateBoardWithWorm (const Worm &a_worm)
This function should be called any time a Worm in m_worms changes state e.g the worm has moved, been eaten, or has died.
void updateBoardWithWormsAndCarrots ()
Set the attrs and characters in the simulation based on the positions of worms and carrots in the simulation.
void makeAllWormsLive ()
bool runSimulationStep (AbstractWormsSimUIStrategy &uiStrategy)
This function executes one simulation step.
void sprinkleCarrots ()
Places a carrot in every passive board square.
void setPassiveSquareAt (square s, int x, int y)
Set the "passive" value of the square at {x,y} in the "board".
square getPassiveSquareAt (int x, int y) const
square getScreenSquareAt (int x, int y) const
Worm & getVictimWorm (Worm &in_worm, int &out_SegementNumber)
Finds a worm other than in_worm that has a segment with index > 0 at the same position as in_worm's head.
void sliceVictim (Worm &victim, int victimSegementNumber)
If an existing slot in is available and victimSegementNumber is
1 and < the number of segments in victim, this function creates
a new worm containing copies of the tail segments up to but not including the segment at victimSegementNumber in victim.
WormsSim (int width, int height)
Constructs a WormsSim instance encapsulating a board with width columns and height rows of squares.
Private Attributes
std::vector< Worm > m_worms
An arbitrary number of worms in the simulation.
std::vector< Worm >::size_type m_high_water_mark
The maximum number of worms that have ever been in the simulation simultaneously (per process invocation)
board m_passive_board
A board used to store non-moving simulation elements i.e.
board m_screen_board
A board used to store information to be directly presented to users.
int m_actual_board_width
The actual width of the simulation's boards.
int m_actual_board_height
The actual hight of the simulation's boards.
Static Private Attributes
static std::random_device rdev {}
static std::default_random_engine random_engine {rdev()}
static const int max_board_width = 100
Arbitrary value.
static const int max_board_height = 100
Arbitrary value.
static const std::vector< std::string > sayings
Stores an arbitrary number of "sayings" which are used when creating Worm instances.
static const int default_square_attr = 0
Arbitrary "display" attributes for each board square.
static const int dead_attribute = 4
Arbitrary "display" attributes for dead worm segments.
static const char carrot = '.'
a carrot indicator char
Detailed Description
WormSim encapsulates the board and zero or more Worm instances.
WormSim provides a runSimulation() function that when called starts or restarts a simulation with a pseudo random number of initial worms and a board containing a carrot in every square. Note: more worms than the initial number may come into existence while the simulation is running. Note: although simulation state is encapsulated by an instance of WormSim, the WormSim functions, runSimulation(), and createWorm(), must be called periodically to modify simulation state over time. Additionally, the WormSim functions, tryToEatCarrotAt(), sliceVictimForWorm(), and eatVictimForWorm(), are called by instances of Worm.
Design Notes:
Following the principle of separation of concerns, the WormSim class intentionally does not have any "drawing" or user input dependencies. It is anticipated that many different strategies for "drawing" a simulation board and the worms may eventually be implemented. Similarly, many different mechanisms for user input may eventually be implemented. WormSim is responsible for encapsulating board state irrespective and decoupled from drawing and user input implemented elsewhere. See Section Use of the Strategy Design Pattern for more information about the decoupling.
Composition ("has-a") relationships are preferred over inheritance ("is-a") relationships between classes. For example, each WormsSim instance has an arbitrary number of Worm instances and has a board. WormsSim has no “virtual” functions suitable for inheritance based polymorphic dispatch.
Definition at line 43 of file WormsSim.h.
Constructor & Destructor Documentation
WormsSim::WormsSim (int width, int height) private
Constructs a WormsSim instance encapsulating a board with width columns and height rows of squares.
If the width or height specified exceeds the values of getMaxBoardWidth() and getMaxBoardHeight() respectively, the maximum values are used. Newly created WormsSim instances have a pseudo random number of living Worm instances of pseudo random types and a board containing a carrot at every position.
Definition at line 67 of file WormsSim.cpp.
References getMaxBoardHeight(), getMaxBoardWidth(), m_actual_board_height, and m_actual_board_width.
Member Function Documentation
std::vector< Worm >::size_type WormsSim::findSlot () const private
Use this function to find an index where a non-living Worm can be replaced by a new living worm.
This approach helps to avoid storing lots and lots of non-living Worms in m_worms. Returns the first index within m_worms that contains a non living worm. Returns m_worms.size() if no suitable index is found.
Definition at line 189 of file WormsSim.cpp.
References m_worms.
unsigned int WormsSim::getRandomModX (unsigned int x) static
Utility function to return a pseudo random natural number in the range 0..(x-1).
Definition at line 78 of file WormsSim.cpp.
Worm & WormsSim::getVictimWorm (Worm & in_worm, int & out_SegementNumber) private
Finds a worm other than in_worm that has a segment with index > 0 at the same position as in_worm's head.
If a suitable worm is found, this function sets out_SegementNumber to the segment number of the found worm's segment at the same position as in_worm's head and returns the found worm.
Otherwise, this function sets out_SegementNumber to 0 and returns in_worm.
Definition at line 282 of file WormsSim.cpp.
References m_worms.
WormsSim & WormsSim::initSingletonSim (int width, int height) static
This function creates an instance of WormsSim with the specified board width and height.
If the width or height specified exceeds the values of getMaxBoardWidth() and getMaxBoardHeight() respectively, the maximum values are used. There can only be one instance of WormsSim at a time. If this function is called when a WormsSim instance containing a board with the specified dimensions already exists, a reference to the pre-existing WormsSim instance is returned. Otherwise, a new WormsSim instance is created that replaces any pre-existing WormsSim instance, and a reference to the new WormsSim instance is returned. Newly created WormsSim instances have a pseudo random number of living Worm instances of pseudo random types. As a side effect, this function resents the counters of live worm instances of each type prior to creating new worm instances that increase the counts.
Definition at line 27 of file WormsSim.cpp.
References WormsSim().
void WormsSim::runSimulation (AbstractWormsSimUIStrategy & uiStrategy)
Each time this function is called, the simulation restarts from initial conditions with a pseudo random number of generated worms and a board containing a carrot at every position.
This function indirectly calls uiStrategy.processUserInput(), and once this function is called, the simulation runs until uiStrategy.processUserInput() returns true. A strategy is able to implement a user interface that accepts user input. The strategy can signal to the WormsSim that the current simulation run should end by returning true from the strategy's implementation of uiStrategy.processUserInput(). Note: more worms than the initial number may come into existence while the simulation is running.
Parameters
uiStrategy The UI strategy that can be used by the running simulation to display simulation state to users and accept user input that controls the simulation.
Definition at line 93 of file WormsSim.cpp.
References findSlot(), Worm::getFoodValue(), getRandomModX(), getVictimWorm(), m_high_water_mark, m_worms, Worm::onWasEaten(), runSimulationStep(), sayings, sliceVictim(), sprinkleCarrots(), and Worm::UniqueWormTypes.
void WormsSim::setPassiveSquareAt (square s, int x, int y) private
Set the "passive" value of the square at {x,y} in the "board".
Passive squares are squares that store information other than living worms e.g. "carrots". A distinction is made between passive squares and others so that worms segments and carrots may occupy the same positions.
Definition at line 209 of file WormsSim.cpp.
References carrot, and m_passive_board.
void WormsSim::sliceVictim (Worm & victim, int victimSegementNumber) private
If an existing slot in is available and victimSegementNumber is
1 and < the number of segments in victim, this function creates
a new worm containing copies of the tail segments up to but not including the segment at victimSegementNumber in victim.
The new worm is stored in the available slot, and victim's onWasSlicedAtSegmentIndex() function is called and may mutate victim. If no new worm is created, this function returns without modifying victim.
Note: Not creating a new worm and not slicing victim just because no existing slot is available seems suspect, but it is consistent with the behavior of the reference pmate.nosp@m.ti@w.nosp@m.right.nosp@m..edu sample code.
Definition at line 328 of file WormsSim.cpp.
References findSlot(), Worm::live(), m_worms, Worm::onWasSlicedAtSegmentIndex(), and Worm::Worm().
void WormsSim::updateBoardWithWorm (const Worm & a_worm) private
This function should be called any time a Worm in m_worms changes state e.g the worm has moved, been eaten, or has died.
Set the attrs and characters in the simulation based on a_worm's current position and status.
Definition at line 243 of file WormsSim.cpp.
References dead_attribute, m_passive_board, and m_screen_board.
Member Data Documentation
const int WormsSim::dead_attribute = 4 static private
Arbitrary "display" attributes for dead worm segments.
Attributes can be any information as long as the information is encoded as a single signed integer. e.g. an attribute might be a key used to look-up graphical properties in a separately maintained dictionary, or an attribute might encode RGB components of a color.
Definition at line 72 of file WormsSim.h.
const int WormsSim::default_square_attr = 0 static private
Arbitrary "display" attributes for each board square.
Attributes can be any information as long as the information is encoded as a single signed integer. e.g. an attribute might be a key used to look-up graphical properties in a separately maintained dictionary, or an attribute might encode RGB components of a color. default_square_attr stores the default value used to initialize each board square.
Definition at line 64 of file WormsSim.h.
board WormsSim::m_passive_board private
A board used to store non-moving simulation elements i.e.
carrots.
Definition at line 101 of file WormsSim.h.
const std::vector< std::string > WormsSim::sayings static private
Initial value:
= {
"*do-not-optimize-too-soon#",
"*If it does not have to be correct, making the program efficient is easy.#",
"*90% of code executes only 10% of the time!#",
"*Is there a program, longer than sayings 1000 lines, that is correct?#",
"*OS is not bug-free, the compiler is not bug-free, so is my program!#",
"*ABCDEFGHIJKLMNOPQRSTUVWXYZ#",
"*98765432109876543210#",
"*Edsger-Dijkstra#",
"*C-A-R-Hoare#",
"*Donald-Knuth#",
"*Richard-Stallman#",
"*Linux-Torvalds#",
}
Stores an arbitrary number of "sayings" which are used when creating Worm instances.
Each string in sayings is potentially used as a source of characters stored in the segments of a worm.
Definition at line 54 of file WormsSim.h.
The documentation for this class was generated from the following files:
WormsSim.h
WormsSim.cpp