Worms: CursesWormsSimUIStrategy Class Reference
CursesWormsSimUIStrategy Class Reference
Instances of CursesWormsSimUIStrategy provide NCurses based graphical display and user interaction of WormsSim instances.
#include <CursesWormsSimUIStrategy.h>
Public Member Functions
CursesWormsSimUIStrategy (WormsSim &sim)
bool confirmExit ()
Call this function to request user interface specific confirmation that the simulation should exit (quit).
WormsSim & getCurrentSim ()
Override of AbstractWormsSimUIStrategy Template Method: Returns the simulation with which the CursesWormsSimUIStrategy was created.
bool processUserInput ()
Override of AbstractWormsSimUIStrategy Template Method: Call his function to perform user interface specific logic including handling of any user input that may have been input since the last call to this function.
void redrawDisplay ()
Override of AbstractWormsSimUIStrategy Template Method: Call his function to request a redraw of the user interface using a user interface specific mechanism.
Static Public Member Functions
static void initializeForDisplay (int &out_width, int &out_height)
Call this function once before calling any other CursesWormsSimUIStrategy functions.
static void releaseDisplay ()
Call this function to make the available display if any being used by CursesWormsSimUIStrategy available for use by other objects.
static int getSlowness ()
Returns the total number of delayQuantum intervals before each call to processUserInput() returns.
static void setSlowness (int aSlowness)
Sets the total number of delayQuantum intervals before each call to processUserInput() returns.
Private Member Functions
int getOneChar ()
Returns one available character of user input.
char handleUserKeyPress (char c)
Perform user interface specific logic in response to user input of the character, c.
void showMessage (std::string text, int y)
Draw specified string of characters on row y on the display.
void showStatus ()
Static Private Member Functions
static void endCurses ()
Call to perform user interface specific shutdown / release of the display being used by the strategy.
static void startCurses (int &asogRows, int &asogCols)
Private Attributes
WormsSim & m_sim
The simulation instance to be displayed in a user interface specific way.
Static Private Attributes
static const char esc = '\033'
static const int rowsInMessageArea = 5
static int slowness = 10
static int delayQuantum = 10
static int delayRemaining
static bool isPaused
static std::map< int, int > wormAttr
A map from integer attribute IDs stored by the simulation to corresponding display attributes in the user interface.
Detailed Description
Instances of CursesWormsSimUIStrategy provide NCurses based graphical display and user interaction of WormsSim instances.
Design Notes:
CursesWormsSimUIStrategy implements the interface specified by the abstract AbstractWormsSimUIStrategy class and participates in the Strategy design pattern to decouple display and user input from simulation encapsulation.
CursesWormsSimUIStrategy adheres to the practical advice from Scott Meyers, “More Effective C++: 35 New Ways to Improve Your Programs and Designs 1st Edition” Item 33, “Make non-leaf classes abstract” as elaborated to use the Template Method design pattern in “Virtuality: C/C++ Users Journal, 19, September 2001” http://www.gotw.ca/publications/mill18.htm
Definition at line 24 of file CursesWormsSimUIStrategy.h.
Member Function Documentation
bool CursesWormsSimUIStrategy::confirmExit ()
Call this function to request user interface specific confirmation that the simulation should exit (quit).
!!!! NOTE: Pre and post conditions are not provided here due to
Definition at line 15 of file CursesWormsSimUIStrategy.cpp.
References getOneChar(), m_sim, and showMessage().
void CursesWormsSimUIStrategy::endCurses () static private
Call to perform user interface specific shutdown / release of the display being used by the strategy.
Definition at line 112 of file CursesWormsSimUIStrategy.cpp.
WormsSim& CursesWormsSimUIStrategy::getCurrentSim () inline virtual
Override of AbstractWormsSimUIStrategy Template Method: Returns the simulation with which the CursesWormsSimUIStrategy was created.
Implements AbstractWormsSimUIStrategy.
Definition at line 107 of file CursesWormsSimUIStrategy.h.
References m_sim, processUserInput(), and redrawDisplay().
int CursesWormsSimUIStrategy::getOneChar () private
Returns one available character of user input.
This function blocks until at least one character is available.
Definition at line 138 of file CursesWormsSimUIStrategy.cpp.
References getSlowness(), m_sim, and showMessage().
char CursesWormsSimUIStrategy::handleUserKeyPress (char c) private
Perform user interface specific logic in response to user input of the character, c.
Definition at line 171 of file CursesWormsSimUIStrategy.cpp.
References m_sim, and wormAttr.
void CursesWormsSimUIStrategy::initializeForDisplay (int & out_width, int & out_height) static
Call this function once before calling any other CursesWormsSimUIStrategy functions.
out_width and out_height respectively are set the the width and height in characters of the available display.
Definition at line 83 of file CursesWormsSimUIStrategy.cpp.
bool CursesWormsSimUIStrategy::processUserInput () virtual
Override of AbstractWormsSimUIStrategy Template Method: Call his function to perform user interface specific logic including handling of any user input that may have been input since the last call to this function.
Regardless of user input, this function does not return for at least getSlowness() number of delayQuantum time intervals have elapsed since the call was made.
Implements AbstractWormsSimUIStrategy.
Definition at line 29 of file CursesWormsSimUIStrategy.cpp.
References handleUserKeyPress().
void CursesWormsSimUIStrategy::redrawDisplay () virtual
Override of AbstractWormsSimUIStrategy Template Method: Call his function to request a redraw of the user interface using a user interface specific mechanism.
Calling this function may result in calls to the strategy's sim to obtain information about what to display.
Implements AbstractWormsSimUIStrategy.
Definition at line 67 of file CursesWormsSimUIStrategy.cpp.
References m_sim, and wormAttr.
void CursesWormsSimUIStrategy::releaseDisplay () static
Call this function to make the available display if any being used by CursesWormsSimUIStrategy available for use by other objects.
Definition at line 93 of file CursesWormsSimUIStrategy.cpp.
References endCurses().
static void CursesWormsSimUIStrategy::setSlowness (int aSlowness) inline static
Sets the total number of delayQuantum intervals before each call to processUserInput() returns.
Change the slowness to speed up or slow down the rate at which the simulation that calls processUserInput() can execute simulation steps.
Definition at line 96 of file CursesWormsSimUIStrategy.h.
References confirmExit().
Member Data Documentation
WormsSim& CursesWormsSimUIStrategy::m_sim private
The simulation instance to be displayed in a user interface specific way.
Definition at line 47 of file CursesWormsSimUIStrategy.h.
std::map< int, int > CursesWormsSimUIStrategy::wormAttr static private
Initial value:
= {
    {0, COLOR_PAIR(4)},
    {1, COLOR_PAIR(1)|A_STANDOUT},
    {2, COLOR_PAIR(2)|A_STANDOUT},
    {3, COLOR_PAIR(3)|A_STANDOUT},
    {4, COLOR_PAIR(4)},
}
A map from integer attribute IDs stored by the simulation to corresponding display attributes in the user interface.
Definition at line 43 of file CursesWormsSimUIStrategy.h.
The documentation for this class was generated from the following files:
CursesWormsSimUIStrategy.h
CursesWormsSimUIStrategy.cpp